# Koristi Node kao bazu
FROM node:18

# Postavi radni direktorijum
WORKDIR /app

# Kopiraj package fajlove
COPY package*.json ./

# Instaliraj zavisnosti
RUN npm install

# Kopiraj ceo frontend kod
COPY . .

# Expose port 3000 za dev server
EXPOSE 3000

# Pokreni React dev server
CMD ["npm", "start"]